site_name: Apache Mesos Tutorial
repo_url: https://github.com/maricaantonacci/mesos-tutorial
site_author: Marica Antonacci - marica.antonacci@ba.infn.it
theme:
  name: material
  palette:
    primary: teal
    accent: green
  logo: assets/logo_infn.png
  features:
    - navigation.sections
    - navigation.expand
    - navigation.top
    - toc.integrate
markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences 
  - pymdownx.snippets
  - pymdownx.tabbed
  - admonition
  - pymdownx.details
  - attr_list
   
nav:
  - Introduction: 'intro.md'
  - Deploy long running services on Marathon: 'marathon.md'
  - Execute scheduled jobs on Chronos: 'chronos.md'
 
copyright: Copyright &copy; 2021 INFN
